export const IMAGES = [
  {
    id: 1,
    src: '/images/adventure1.jpg',
    alt: 'adventure',
    title: 'adventure',
  },
  {
    id: 2,
    src: '/images/adventure2.jpg',
    alt: 'adventure',
    title: 'adventure',
  },
  {
    id: 3,
    src: '/images/adventure3.jpg',
    alt: 'adventure',
    title: 'adventure',
  },
  {
    id: 4,
    src: '/images/adventure4.jpg',
    alt: 'adventure',
    title: 'adventure',
  },
  {
    id: 5,
    src: '/images/adventure5.jpg',
    alt: 'adventure',
    title: 'adventure',
  },
  { id: 6, src: '/images/history1.jpg', alt: 'history', title: 'history' },
  { id: 7, src: '/images/history2.jpg', alt: 'history', title: 'history' },
  { id: 8, src: '/images/history3.jpg', alt: 'history', title: 'history' },
  { id: 9, src: '/images/history4.jpg', alt: 'history', title: 'history' },
  { id: 10, src: '/images/history5.jpg', alt: 'history', title: 'history' },
  { id: 11, src: '/images/fantasy1.jpg', alt: 'fantasy', title: 'fantasy' },
  { id: 12, src: '/images/fantasy2.jpg', alt: 'fantasy', title: 'fantasy' },
  { id: 13, src: '/images/fantasy3.jpg', alt: 'fantasy', title: 'fantasy' },
  { id: 14, src: '/images/fantasy4.jpg', alt: 'fantasy', title: 'fantasy' },
  { id: 15, src: '/images/fantasy5.jpg', alt: 'fantasy', title: 'fantasy' },
  { id: 16, src: '/images/selfHelp1.jpg', alt: 'selfHelp', title: 'selfHelp' },
  { id: 17, src: '/images/selfHelp2.jpg', alt: 'selfHelp', title: 'selfHelp' },
  { id: 18, src: '/images/selfHelp3.jpg', alt: 'selfHelp', title: 'selfHelp' },
  { id: 19, src: '/images/selfHelp4.jpg', alt: 'selfHelp', title: 'selfHelp' },
  { id: 20, src: '/images/selfHelp5.jpg', alt: 'selfHelp', title: 'selfHelp' },
];
